### ISSUE TITLE
NameError: name 'mapq' is not defined. Did you mean: 'map'?

### ISSUE THREAD

**Issue by Zjianglin** [Jyyin333/Ucaps-seq#1]
Hi developer, I tried run the `Ucaps-seq` according to your tutorial and your deposited data (`HEK293T`) excepted the reference genome `GRCh38` was used.  After reads mapping and sorted by coordinate, I tried run the `snakemake` pipeline to analyze the dataset. However, it crashed at `rule fetch_dU_by_chrom:`. Here is the error log:
```
INFO    2022-09-06 00:58:48     MarkDuplicates  Written   390,000,000 records.  Elapsed time: 01:27:13s.  Time for last 10,000,000:  1
48s.  Last read position: chrUn_GL000214v1:125,319
INFO    2022-09-06 00:59:44     MarkDuplicates  Writing complete. Closing input iterator.
INFO    2022-09-06 00:59:44     MarkDuplicates  Duplicate Index cleanup.
INFO    2022-09-06 00:59:44     MarkDuplicates  Getting Memory Stats.
INFO    2022-09-06 00:59:49     MarkDuplicates  Before output close freeMemory: 1274026976; totalMemory: 1291845632; maxMemory: 103079
215104
INFO    2022-09-06 00:59:49     MarkDuplicates  Closed outputs. Getting more Memory Stats.
INFO    2022-09-06 00:59:49     MarkDuplicates  After output close freeMemory: 322423680; totalMemory: 335544320; maxMemory: 103079215
104
[Tue Sep 06 00:59:49 CST 2022] picard.sam.markduplicates.MarkDuplicates done. Elapsed time: 136.84 minutes.
Runtime.totalMemory()=335544320
[Tue Sep  6 00:59:49 2022]
Finished job 90.
1 of 175 steps (1%) done

[Tue Sep  6 00:59:49 2022]
rule fetch_dU_by_chrom:
    input: post_bams/SRR14477837_sorted_dedup.bam, post_bams/SRR14477837_sorted_dedup.bai
    output: SRR14477837.chr20.raw.bed
    jobid: 109
    reason: Missing output files: SRR14477837.chr20.raw.bed; Input files updated by another job: post_bams/SRR14477837_sorted_dedup.bai, post_bams/SRR14477837_sorted_dedup.bam
    wildcards: sm=SRR14477837, i=20
    resources: tmpdir=/tmp


[Tue Sep  6 00:59:49 2022]
rule fetch_dU_by_chrom:
    input: post_bams/SRR14477837_sorted_dedup.bam, post_bams/SRR14477837_sorted_dedup.bai
    output: SRR14477837.chr18.raw.bed
    jobid: 107
    reason: Missing output files: SRR14477837.chr18.raw.bed; Input files updated by another job: post_bams/SRR14477837_sorted_dedup.bai, post_bams/SRR14477837_sorted_dedup.bam
    wildcards: sm=SRR14477837, i=18
    resources: tmpdir=/tmp
[Tue Sep  6 00:59:49 2022]
rule fetch_dU_by_chrom:
    input: post_bams/SRR14477837_sorted_dedup.bam, post_bams/SRR14477837_sorted_dedup.bai
    output: SRR14477837.chr12.raw.bed
    jobid: 101
    reason: Missing output files: SRR14477837.chr12.raw.bed; Input files updated by another job: post_bams/SRR14477837_sorted_dedup.bai, post_bams/SRR14477837_sorted_dedup.bam
    wildcards: sm=SRR14477837, i=12
    resources: tmpdir=/tmp


[Tue Sep  6 00:59:49 2022]
rule dedup:
    input: pp_bams/SRR14477825_sorted.bam, pp_bams/SRR14477825_sorted.bai
    output: post_bams/SRR14477825_sorted_dedup.bam, post_bams/SRR14477825_sorted_dedup.bai, post_bams/SRR14477825_sorted_dedup.metrics
    jobid: 34
    reason: Missing output files: post_bams/SRR14477825_sorted_dedup.bam, post_bams/SRR14477825_sorted_dedup.bai
    wildcards: sm=SRR14477825
    threads: 5
    resources: tmpdir=/tmp


Traceback (most recent call last):
  File "/data/westd18t/datasets/22JACS_Ucaps_seq/Ucapsseq/HEK293T.bwa/scripts/fetch_dU_by_chrom.py", line 102, in <module>
    main()
  File "/data/westd18t/datasets/22JACS_Ucaps_seq/Ucapsseq/HEK293T.bwa/scripts/fetch_dU_by_chrom.py", line 73, in main
    score = 1000 - mapq
NameError: name 'mapq' is not defined. Did you mean: 'map'?
Traceback (most recent call last):
  File "/data/westd18t/datasets/22JACS_Ucaps_seq/Ucapsseq/HEK293T.bwa/scripts/fetch_dU_by_chrom.py", line 102, in <module>
    main()
  File "/data/westd18t/datasets/22JACS_Ucaps_seq/Ucapsseq/HEK293T.bwa/scripts/fetch_dU_by_chrom.py", line 89, in main
    score = mapq
NameError: name 'mapq' is not defined. Did you mean: 'map'?
Traceback (most recent call last):
  File "/data/westd18t/datasets/22JACS_Ucaps_seq/Ucapsseq/HEK293T.bwa/scripts/fetch_dU_by_chrom.py", line 102, in <module>
    main()
  File "/data/westd18t/datasets/22JACS_Ucaps_seq/Ucapsseq/HEK293T.bwa/scripts/fetch_dU_by_chrom.py", line 89, in main
    score = mapq
NameError: name 'mapq' is not defined. Did you mean: 'map'?
[Tue Sep  6 00:59:50 2022]
Error in rule fetch_dU_by_chrom:
    jobid: 101
    output: SRR14477837.chr12.raw.bed
    shell:
        python scripts/fetch_dU_by_chrom.py             --ref_fa /data/amax81t/Databases/GRCh38/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna                 --bam post_bams/SRR14477837_sorted_dedup.bam            --out_file SRR14477837.chr12.raw.bed            --chrom chr12           
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job fetch_dU_by_chrom since they might be corrupted:
SRR14477837.chr12.raw.bed
[Tue Sep  6 00:59:50 2022]

rror in rule fetch_dU_by_chrom:
    jobid: 109
    output: SRR14477837.chr20.raw.bed
    shell:
        python scripts/fetch_dU_by_chrom.py             --ref_fa /data/amax81t/Databases/GRCh38/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna                 --bam post_bams/SRR14477837_sorted_dedup.bam            --out_file SRR14477837.chr20.raw.bed            --chrom chr20           
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job fetch_dU_by_chrom since they might be corrupted:
SRR14477837.chr20.raw.bed
[Tue Sep  6 00:59:50 2022]
Error in rule fetch_dU_by_chrom:
    jobid: 107
    output: SRR14477837.chr18.raw.bed
    shell:
        python scripts/fetch_dU_by_chrom.py             --ref_fa /data/amax81t/Databases/GRCh38/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna                 --bam post_bams/SRR14477837_sorted_dedup.bam            --out_file SRR14477837.chr18.raw.bed            --chrom chr18           
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
.....

```

I checked the script `fetch_dU_by_chrom.py` and two lines used variable `mapq` but no declaration or assignment. Could you please help me?

**Comment by Jyyin333** [comment]
Hi, 
	Thank you to pointing out the mistake, and I have fixed it.
	Contact me plz if you have any other questions.


Jyyin,
Best regards

发件人: Zjianglin
发送时间: 2022年9月6日 13:05
收件人: Jyyin333/Ucaps-seq
抄送: Subscribed
主题: [Jyyin333/Ucaps-seq] NameError: name 'mapq' is not defined. Did youmean: 'map'? (Issue #1)

Hi developer, I tried run the Ucaps-seq according to your tutorial and your deposited data (HEK293T) excepted the reference genome GRCh38 was used. After reads mapping and sorted by coordinate, I tried run the snakemake pipeline to analyze the dataset. However, it crashed at rule fetch_dU_by_chrom:. Here is the error log:
INFO    2022-09-06 00:58:48     MarkDuplicates  Written   390,000,000 records.  Elapsed time: 01:27:13s.  Time for last 10,000,000:  1
48s.  Last read position: chrUn_GL000214v1:125,319
INFO    2022-09-06 00:59:44     MarkDuplicates  Writing complete. Closing input iterator.
INFO    2022-09-06 00:59:44     MarkDuplicates  Duplicate Index cleanup.
INFO    2022-09-06 00:59:44     MarkDuplicates  Getting Memory Stats.
INFO    2022-09-06 00:59:49     MarkDuplicates  Before output close freeMemory: 1274026976; totalMemory: 1291845632; maxMemory: 103079
215104
INFO    2022-09-06 00:59:49     MarkDuplicates  Closed outputs. Getting more Memory Stats.
INFO    2022-09-06 00:59:49     MarkDuplicates  After output close freeMemory: 322423680; totalMemory: 335544320; maxMemory: 103079215
104
[Tue Sep 06 00:59:49 CST 2022] picard.sam.markduplicates.MarkDuplicates done. Elapsed time: 136.84 minutes.
Runtime.totalMemory()=335544320
[Tue Sep  6 00:59:49 2022]
Finished job 90.
1 of 175 steps (1%) done

[Tue Sep  6 00:59:49 2022]
rule fetch_dU_by_chrom:
    input: post_bams/SRR14477837_sorted_dedup.bam, post_bams/SRR14477837_sorted_dedup.bai
    output: SRR14477837.chr20.raw.bed
    jobid: 109
    reason: Missing output files: SRR14477837.chr20.raw.bed; Input files updated by another job: post_bams/SRR14477837_sorted_dedup.bai, post_bams/SRR14477837_sorted_dedup.bam
    wildcards: sm=SRR14477837, i=20
    resources: tmpdir=/tmp


[Tue Sep  6 00:59:49 2022]
rule fetch_dU_by_chrom:
    input: post_bams/SRR14477837_sorted_dedup.bam, post_bams/SRR14477837_sorted_dedup.bai
    output: SRR14477837.chr18.raw.bed
    jobid: 107
    reason: Missing output files: SRR14477837.chr18.raw.bed; Input files updated by another job: post_bams/SRR14477837_sorted_dedup.bai, post_bams/SRR14477837_sorted_dedup.bam
    wildcards: sm=SRR14477837, i=18
    resources: tmpdir=/tmp
[Tue Sep  6 00:59:49 2022]
rule fetch_dU_by_chrom:
    input: post_bams/SRR14477837_sorted_dedup.bam, post_bams/SRR14477837_sorted_dedup.bai
    output: SRR14477837.chr12.raw.bed
    jobid: 101
    reason: Missing output files: SRR14477837.chr12.raw.bed; Input files updated by another job: post_bams/SRR14477837_sorted_dedup.bai, post_bams/SRR14477837_sorted_dedup.bam
    wildcards: sm=SRR14477837, i=12
    resources: tmpdir=/tmp


[Tue Sep  6 00:59:49 2022]
rule dedup:
    input: pp_bams/SRR14477825_sorted.bam, pp_bams/SRR14477825_sorted.bai
    output: post_bams/SRR14477825_sorted_dedup.bam, post_bams/SRR14477825_sorted_dedup.bai, post_bams/SRR14477825_sorted_dedup.metrics
    jobid: 34
    reason: Missing output files: post_bams/SRR14477825_sorted_dedup.bam, post_bams/SRR14477825_sorted_dedup.bai
    wildcards: sm=SRR14477825
    threads: 5
    resources: tmpdir=/tmp


Traceback (most recent call last):
  File "/data/westd18t/datasets/22JACS_Ucaps_seq/Ucapsseq/HEK293T.bwa/scripts/fetch_dU_by_chrom.py", line 102, in <module>
    main()
  File "/data/westd18t/datasets/22JACS_Ucaps_seq/Ucapsseq/HEK293T.bwa/scripts/fetch_dU_by_chrom.py", line 73, in main
    score = 1000 - mapq
NameError: name 'mapq' is not defined. Did you mean: 'map'?
Traceback (most recent call last):
  File "/data/westd18t/datasets/22JACS_Ucaps_seq/Ucapsseq/HEK293T.bwa/scripts/fetch_dU_by_chrom.py", line 102, in <module>
    main()
  File "/data/westd18t/datasets/22JACS_Ucaps_seq/Ucapsseq/HEK293T.bwa/scripts/fetch_dU_by_chrom.py", line 89, in main
    score = mapq
NameError: name 'mapq' is not defined. Did you mean: 'map'?
Traceback (most recent call last):
  File "/data/westd18t/datasets/22JACS_Ucaps_seq/Ucapsseq/HEK293T.bwa/scripts/fetch_dU_by_chrom.py", line 102, in <module>
    main()
  File "/data/westd18t/datasets/22JACS_Ucaps_seq/Ucapsseq/HEK293T.bwa/scripts/fetch_dU_by_chrom.py", line 89, in main
    score = mapq
NameError: name 'mapq' is not defined. Did you mean: 'map'?
[Tue Sep  6 00:59:50 2022]
Error in rule fetch_dU_by_chrom:
    jobid: 101
    output: SRR14477837.chr12.raw.bed
    shell:
        python scripts/fetch_dU_by_chrom.py             --ref_fa /data/amax81t/Databases/GRCh38/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna                 --bam post_bams/SRR14477837_sorted_dedup.bam            --out_file SRR14477837.chr12.raw.bed            --chrom chr12           
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job fetch_dU_by_chrom since they might be corrupted:
SRR14477837.chr12.raw.bed
[Tue Sep  6 00:59:50 2022]

rror in rule fetch_dU_by_chrom:
    jobid: 109
    output: SRR14477837.chr20.raw.bed
    shell:
        python scripts/fetch_dU_by_chrom.py             --ref_fa /data/amax81t/Databases/GRCh38/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna                 --bam post_bams/SRR14477837_sorted_dedup.bam            --out_file SRR14477837.chr20.raw.bed            --chrom chr20           
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job fetch_dU_by_chrom since they might be corrupted:
SRR14477837.chr20.raw.bed
[Tue Sep  6 00:59:50 2022]
Error in rule fetch_dU_by_chrom:
    jobid: 107
    output: SRR14477837.chr18.raw.bed
    shell:
        python scripts/fetch_dU_by_chrom.py             --ref_fa /data/amax81t/Databases/GRCh38/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna                 --bam post_bams/SRR14477837_sorted_dedup.bam            --out_file SRR14477837.chr18.raw.bed            --chrom chr18           
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
.....

I checked the script fetch_dU_by_chrom.py and two lines used variable mapq but no declaration or assignment. Could you please help me?
